// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApplication1.data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DBC))]
    partial class DBCModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("WebApplication1.Models.mainm", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("user1id");

                    b.Property<int?>("user2id");

                    b.HasKey("id");

                    b.HasIndex("user1id");

                    b.HasIndex("user2id");

                    b.ToTable("mainm");
                });

            modelBuilder.Entity("WebApplication1.Models.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("WebApplication1.Models.mainm", b =>
                {
                    b.HasOne("WebApplication1.Models.user", "user1")
                        .WithMany()
                        .HasForeignKey("user1id");

                    b.HasOne("WebApplication1.Models.user", "user2")
                        .WithMany()
                        .HasForeignKey("user2id");
                });
#pragma warning restore 612, 618
        }
    }
}
